# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-24 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0003_meetuptype_has_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='meetup_url',
            field=models.URLField(blank=True),
        ),
    ]
