FROM python:3.13

RUN mkdir /opt/meetpy

WORKDIR /opt/meetpy

ADD requirements.txt /opt/meetpy/requirements.txt
ADD requirements-pg.txt /opt/meetpy/requirements-pg.txt

RUN pip install pip-tools
RUN pip install --no-cache-dir --requirement requirements.txt
RUN pip install --no-cache-dir --requirement requirements-pg.txt

ADD meetpy/ /opt/meetpy/meetpy

ENV DJANGO_SETTINGS_MODULE="meetpy.settings.docker"

WORKDIR /opt/meetpy/meetpy

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
