version: '3'

services:
  meetpy:
    image: meetpy
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app/meetpy
    ports:
      - "18000:8000"
    tty: true
    depends_on:
      - db
      - smtp
    environment:
      - DEBUG=True
      - SECRET_KEY=!!!UNSAFE_KEY!!!
      - DATABASE_URL=psql://usr:pass@db:5432/meetpy
      - EMAIL_URL=smtp://smtp:1025

  smtp:
      image: sj26/mailcatcher
      ports:
        - "1025:1025"
        - "8081:1080"

  db:
      image: postgres:9.6
      restart: unless-stopped
      ports:
        - "15432:5432"
      environment:
        - POSTGRES_USER=usr
        - POSTGRES_PASSWORD=pass
        - POSTGRES_DB=meetpy
      volumes:
        - dbdata:/var/lib/postgresql/data/

  phppgadmin:
    image: dockage/phppgadmin
    ports:
    - "8082:80"
    environment:
    - PHP_PG_ADMIN_SERVER_DESC=PostgreSQL
    - PHP_PG_ADMIN_SERVER_HOST=db
    - PHP_PG_ADMIN_SERVER_PORT=5432

volumes:
  dbdata:
    driver: local
