FROM python:3.7.4

RUN mkdir /opt/meetpy

WORKDIR /opt/meetpy

ADD requirements.txt /opt/meetpy/

RUN pip install --no-cache-dir --requirement requirements.txt

ADD meetpy/ /opt/meetpy/meetpy

ENV DJANGO_SETTINGS_MODULE="meetpy.settings.docker"

WORKDIR /opt/meetpy/meetpy

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
