version: '3'

services:
  meetpy:
    image: meetpy
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app/meetpy
    ports:
      - "18000:8000"
    tty: true
    depends_on:
      - db
      - smtp
    environment:
      - DEBUG=True
      - SECRET_KEY=!!!UNSAFE_KEY!!!
      - DATABASE_URL=psql://usr:pass@db:5432/meetpy
      - EMAIL_URL=smtp://smtp:1025

  smtp:
      image: sj26/mailcatcher

  db:
      image: postgres:9.6
      restart: unless-stopped
      environment:
        - POSTGRES_USER=usr
        - POSTGRES_PASSWORD=pass
        - POSTGRES_DB=meetpy
      volumes:
        - dbdata:/var/lib/postgresql/data/

volumes:
  dbdata:
    driver: local
