# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-17 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0004_meetup_meetup_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetuptype',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetup',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
