# Generated by Django 2.1 on 2019-11-13 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_add_slug_to_type_and_make_meetup_number_not_unique'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[
            migrations.CreateModel(
                name='MeetupSponsorThrough',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ],
                options={
                    'db_table': 'meetups_meetup_sponsors',
                },
            ),
            migrations.AlterField(
                model_name='meetup',
                name='sponsors',
                field=models.ManyToManyField(blank=True, related_name='sponsored_meetups', through='meetups.MeetupSponsorThrough', to='meetups.Sponsor'),
            ),
            migrations.AddField(
                model_name='meetupsponsorthrough',
                name='meetup',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetups.Meetup'),
            ),
            migrations.AddField(
                model_name='meetupsponsorthrough',
                name='sponsor',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetups.Sponsor'),
            )
        ])
    ]
