# Generated by Django 2.1.11 on 2019-11-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_add_slug_to_type_and_make_meetup_number_not_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='without_owner',
            field=models.BooleanField(default=False),
        ),
    ]
