# Generated by Django 3.2.15 on 2022-09-20 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0006_talk_without_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkproposal',
            name='talk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='meetups.talk'),
        ),
    ]
