# Generated by Django 2.1 on 2019-11-24 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0006_talk_without_owner'),
        ('meetups', '0006_auto_20191113_1942'),
    ]

    operations = [
    ]
