# Generated by Django 3.2.15 on 2023-09-29 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0010_add_sponsor_ordering_per_meetup'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetupsponsorthrough',
            name='meetup_description',
            field=models.TextField(blank=True),
        ),
    ]
