# Generated by Django 3.2.15 on 2023-10-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetups", "0011_add_sponsor_meetup_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetup",
            name="is_draft",
            field=models.BooleanField(
                default=False,
                help_text="Meeting will not be shown on main page and meetings list when checked",
            ),
        ),
        migrations.AlterField(
            model_name="meetup",
            name="is_ready",
            field=models.BooleanField(
                default=False,
                help_text='Meeting will display "Agenda in preparation" below talks when unchecked',
                verbose_name="Is agenda ready",
            ),
        ),
        migrations.AlterField(
            model_name="meetup",
            name="is_draft",
            field=models.BooleanField(
                default=True,
                help_text="Meeting will not be shown on main page and meetings list when checked",
            ),
        ),
    ]
