# Generated by Django 3.2.15 on 2023-10-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetups", "0011_add_sponsor_meetup_description"),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
