# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-24 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_auto_20171124_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetuptype',
            name='has_agenda',
            field=models.BooleanField(default=True),
        ),
    ]
