# .github/workflows/ci.yml
name: Build

on: [push, pull_request]

env:
  DJANGO_SETTINGS_MODULE: "meetpy.settings.ci"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run migrations
        run: ./manage.py migrate
        working-directory: meetpy

      - name: Run tests
        run: pytest
        working-directory: meetpy
